name: "Deploy"
description: "Deploy app"

inputs:
  username:
    description: username
    required: true
  password:
    description: password
    required: true

outputs:
  result:
    description: result
  time:
    description: time

runs:
  using: docker
  image: Dockerfile
